// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJ4kc6CtJos6c3lv0Iz17woCRO8GVGs7c',
    appId: '1:758692455460:web:cb4776e091014e7bb2a4b1',
    messagingSenderId: '758692455460',
    projectId: 'cocomakers-sound-classify-app',
    authDomain: 'cocomakers-sound-classify-app.firebaseapp.com',
    storageBucket: 'cocomakers-sound-classify-app.appspot.com',
    measurementId: 'G-M1BQC9XPQF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7RWt0Bkbc6MRStludNEofSzIp4kZQ1HQ',
    appId: '1:758692455460:android:6208e8327d4955c5b2a4b1',
    messagingSenderId: '758692455460',
    projectId: 'cocomakers-sound-classify-app',
    storageBucket: 'cocomakers-sound-classify-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHuigZYdvllvHpQi8uRKWH8oy5oOcCtyQ',
    appId: '1:758692455460:ios:9d9561ec1573d77ab2a4b1',
    messagingSenderId: '758692455460',
    projectId: 'cocomakers-sound-classify-app',
    storageBucket: 'cocomakers-sound-classify-app.appspot.com',
    iosBundleId: 'com.example.soundMapApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHuigZYdvllvHpQi8uRKWH8oy5oOcCtyQ',
    appId: '1:758692455460:ios:9d9561ec1573d77ab2a4b1',
    messagingSenderId: '758692455460',
    projectId: 'cocomakers-sound-classify-app',
    storageBucket: 'cocomakers-sound-classify-app.appspot.com',
    iosBundleId: 'com.example.soundMapApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJ4kc6CtJos6c3lv0Iz17woCRO8GVGs7c',
    appId: '1:758692455460:web:0168aad5b494c7e7b2a4b1',
    messagingSenderId: '758692455460',
    projectId: 'cocomakers-sound-classify-app',
    authDomain: 'cocomakers-sound-classify-app.firebaseapp.com',
    storageBucket: 'cocomakers-sound-classify-app.appspot.com',
    measurementId: 'G-R575Z2XS8X',
  );
}
